###############################################################################
# Makefile for the project GLCD_Test
###############################################################################

## General Flags
PROJECT = GLCD_Test
MCU = atmega16
TARGET = GLCD_Test.elf
CC = avr-gcc

## Options common to compile, link and assembly rules
COMMON = -mmcu=$(MCU)

## Compile options common for all C compilation units.
CFLAGS = $(COMMON)
CFLAGS += -Wall -gdwarf-2 -std=gnu99 -O3 -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums
CFLAGS += -MD -MP -MT $(*F).o -MF dep/$(@F).d 

## Assembly specific flags
ASMFLAGS = $(COMMON)
ASMFLAGS += $(CFLAGS)
ASMFLAGS += -x assembler-with-cpp -Wa,-gdwarf2

## Linker flags
LDFLAGS = $(COMMON)
LDFLAGS +=  -Wl,-Map=GLCD_Test.map


## Intel Hex file production flags
HEX_FLASH_FLAGS = -R .eeprom -R .fuse -R .lock -R .signature

HEX_EEPROM_FLAGS = -j .eeprom
HEX_EEPROM_FLAGS += --set-section-flags=.eeprom="alloc,load"
HEX_EEPROM_FLAGS += --change-section-lma .eeprom=0 --no-change-warnings


## Objects that must be built in order to link
OBJECTS = Atmega16_TI_RF.o Timer0.o Uart.o Dio_c.o LCD_Mode4.o SW_TIMER.o Switch_c.o 

## Objects explicitly added by the user
LINKONLYOBJECTS = 

## Build
all: $(TARGET) GLCD_Test.hex GLCD_Test.eep GLCD_Test.lss size

## Compile
Atmega16_TI_RF.o: ../Atmega16_TI_RF.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

Timer0.o: ../Timer0.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

Uart.o: ../Uart.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

Dio_c.o: ../Dio_c.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

LCD_Mode4.o: ../LCD_Mode4.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

SW_TIMER.o: ../SW_TIMER.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

Switch_c.o: ../Switch_c.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

##Link
$(TARGET): $(OBJECTS)
	 $(CC) $(LDFLAGS) $(OBJECTS) $(LINKONLYOBJECTS) $(LIBDIRS) $(LIBS) -o $(TARGET)

%.hex: $(TARGET)
	avr-objcopy -O ihex $(HEX_FLASH_FLAGS)  $< $@

%.eep: $(TARGET)
	-avr-objcopy $(HEX_EEPROM_FLAGS) -O ihex $< $@ || exit 0

%.lss: $(TARGET)
	avr-objdump -h -S $< > $@

size: ${TARGET}
	@echo
	@avr-size -C --mcu=${MCU} ${TARGET}

## Clean target
.PHONY: clean
clean:
	-rm -rf $(OBJECTS) GLCD_Test.elf dep/* GLCD_Test.hex GLCD_Test.eep GLCD_Test.lss GLCD_Test.map


## Other dependencies
-include $(shell mkdir dep 2>/dev/null) $(wildcard dep/*)

